image:
  - Visual Studio 2019
  - Ubuntu
  - macOS

version: 3.0.0-preview-05-b{build}

test: off

skip_commits:
  message: /skipci .*/

build_script:
  - dotnet run  -f netcoreapp3.1 -c Release -p test/FastExpressionCompiler.TestsRunner/FastExpressionCompiler.TestsRunner.csproj

for:
  - matrix:
      only:
        - image: Visual Studio 2019

    build_script:
      - build_with_packaging.bat

    artifacts:
      - path: .\.dist\*.nupkg
